### ISSUE TITLE
Probably worth mentioning what inputs/filters/outputs logstash-contrib adds.

### ISSUE THREAD

**Issue by shurane** [elastic/logstash-contrib#89]
Definitely should be placed in the README.md. I can't tell what `logstash-contrib` offers just by looking at http://logstash.net/docs/1.4.2/contrib-plugins

**Comment by jordansissel** [comment]
@shurane that's a good idea :)

With Logstash 1.5.0, the 'contrib' package/repo was split into many individual repos and plugins (https://github.com/logstash-plugins) that are installable and upgradable separately from Logstash releases, which is totally sweet. You can read more about this change [on our blog](https://www.elastic.co/blog/plugin-ecosystem-changes).

If you have questions, let us know on https://discuss.elastic.co/, but otherwise I think we can close this since contrib is gone in 1.5.0 in favor of the new plugins ecosystem.
